version: '2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /srv/db/data:/var/lib/postgresql/data/

  redis:
    image: redis:3-alpine

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.release
    env_file: ./.env
    image: tsdp/backend
    volumes:
      - backend-static:/srv/app/static/
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis

  celery:
    image: tsdp/backend
    restart: always
    env_file: ./.env
    environment:
      - DEBUG=off
    command: celery -A tsdp worker -l info
    links:
      - redis:redis
      - db:db
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:stable-alpine
    restart: always
    environment:
      - NGINX_HOST=${NGINX_HOST}
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/default.template:/tmp/default.template
      - backend-static:/srv/static:ro
    links:
      - backend:backend
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /tmp/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  backend-static:
