# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('strategies', '0004_auto_20170904_1017'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(3, 'Collective2'), (2, 'Interactive Brokers'), (1, 'Simulator')], db_index=True,
                verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards',
                                    to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='boardfield',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='game.Board',
                                    verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='boardfield',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields',
                                    to='strategies.Strategy', verbose_name='Strategy'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chips', to='game.Board',
                                    verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='fields',
            field=models.ManyToManyField(related_name='chips', to='game.BoardField', verbose_name='Board fields'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='instruments',
            field=models.ManyToManyField(related_name='chips', through='game.ChipHasInstrument', to='quotes.Instrument',
                                         verbose_name='Instruments'),
        ),
        migrations.AlterField(
            model_name='order',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='game.Board',
                                    verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='order',
            name='chip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='game.Chip',
                                    verbose_name='Chip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
                                    to='quotes.Instrument', verbose_name='Instrument'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='signals',
        ),
        migrations.AddField(
            model_name='order',
            name='signals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
                                    to='strategies.Signal', verbose_name='Signal'),
            preserve_default=False,
        ),
    ]
