# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('quotes', '0001_initial'),
        ('game', '0002_auto_20170904_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipInstruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='chiphasinstrument',
            name='chip',
        ),
        migrations.RemoveField(
            model_name='chiphasinstrument',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='chip',
            name='target_volatility',
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(3, 'Collective2'), (2, 'Interactive Brokers'), (1, 'Simulator')], db_index=True, default=1,
                verbose_name='type'),
        ),
        migrations.RemoveField(
            model_name='chip',
            name='fields',
        ),
        migrations.AddField(
            model_name='chip',
            name='fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chips',
                                    to='game.BoardField', verbose_name='Board field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chip',
            name='instruments',
            field=models.ManyToManyField(related_name='chips', through='game.ChipInstruments', to='quotes.Instrument',
                                         verbose_name='Instruments'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Immediate'), (1, 'Market-on-close')], db_index=True,
                                                   verbose_name='type'),
        ),
        migrations.DeleteModel(
            name='ChipHasInstrument',
        ),
        migrations.AddField(
            model_name='chipinstruments',
            name='chip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Chip'),
        ),
        migrations.AddField(
            model_name='chipinstruments',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Instrument'),
        ),
        migrations.AlterUniqueTogether(
            name='chipinstruments',
            unique_together=set([('chip', 'instrument')]),
        ),
    ]
