# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type',
                 models.SmallIntegerField(choices=[(1, 'buy'), (-1, 'sell'), (0, 'close')], verbose_name='type')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='create date')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Instrument')),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signals',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.Strategy'),
        ),
    ]
