# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='create_date',
        ),
        migrations.AddField(
            model_name='signal',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='create datetime'),
            preserve_default=False,
        ),
    ]
